### ISSUE TITLE
Classes to define response structure from graylog

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/logpanel#19]
Graylog sends us data structures that follow patterns. Part of the power of TypeScript is being able to define classes that represent these structures, so that we can
- Validate that we receive data in the shape we expect
- Validate that we are using it correctly in our code
- Have code completion in our IDEs when playing with this data.

For this issue, take the structures that we currently receive from graylog and define classes to represent it, then use them in place of objects.

**Comment by TBThomas56** [comment]
https://github.com/DiamondLightSource/logpanel/pull/18#discussion_r1575092300

**Comment by TBThomas56** [comment]
https://github.com/DiamondLightSource/logpanel/pull/18#discussion_r1575096336

**Comment by TBThomas56** [comment]
https://github.com/DiamondLightSource/logpanel/pull/18#discussion_r1575096336

**Comment by TBThomas56** [comment]
https://github.com/DiamondLightSource/logpanel/pull/20#pullrequestreview-2028528468

**Comment by TBThomas56** [comment]
https://github.com/DiamondLightSource/logpanel/pull/20#discussion_r1583273434
